#* name:     MonoLisa Dark
#* author:   marliqn
#* upstream: https://github.com/marliqn/MonoLisa/Ports/Kitty/monolisa-dark.conf


background              #14110F
background_alt          #1B1613
surface                 #231C18
surface_high            #2C231E
active_tab_foreground   #1B1613
active_tab_background   #C69A5B

inactive_tab_foreground #A89C8A
inactive_tab_background #1A1411

tab_bar_background      #1B1613

foreground              #E8DCC0
foreground_dim          #B8AA94
foreground_faint        #7E7466

cursor                  #D0A060
cursor_text_color       #1B1613

selection_background    #3A2F28
selection_foreground    #F2E6C9

mark1_foreground #1B1613
mark1_background #D4A373

mark2_foreground #1B1613
mark2_background #B5655D

mark3_foreground #1B1613
mark3_background #7C9A92

color0  #1A1411
color8  #6B5A4F

color1  #A14F3F
color9  #C26152

color2  #7A8B5A
color10 #93A86A

color3  #C69A5B
color11 #E0B97A

color4  #7E9098
color12 #9FB3BD

color5  #8C5A6B
color13 #A87486

color6  #6F8F88
color14 #8FB3AA

color7  #E8DCC0
color15 #F4ECD8

