## name:     MonoLisa Dark
## author:   marliqn
## upstream: https://github.com/marliqn/MonoLisa/Ports/Kitty/monolisa-dark.conf


background            #080808
background_alt        #141012
surface               #21191c
surface_high          #2b2024
active_tab_foreground   #141012
active_tab_background   #d48c3f

inactive_tab_foreground #b7a88a
inactive_tab_background #1a1417

tab_bar_background      #141012

foreground            #e4d2a2
foreground_dim        #b7a88a
foreground_faint      #8a7d69

cursor                #d48c3f
cursor_text_color     #141012

selection_background  #3b2a20
selection_foreground  #f2e3b6

# Colors for marks (marked text in the terminal):
mark1_foreground #141012
mark1_background #f2a65a
mark2_foreground #141012
mark2_background #e17888
mark3_foreground #141012
mark3_background #8fbfc6

# black:
color0  #1a1315
color8  #5c464a

# red:
color1  #c34b3a
color9  #e2604a

# green:
color2  #8a9d3f
color10 #a9c24d

# yellow:
color3  #d28c3f
color11 #f2a65a

# blue:
color4  #6f9096
color12 #8fbfc6

# magenta:
color5  #c05c6b
color13 #e17888

# cyan:
color6  #6ea88c
color14 #8fd3ab

# white:
color7  #e4d2a2
color15 #f6e8c8
